helpout/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.IndexTemplateView.as_view(), name="main_menu"),
    path("volah/", include("volah.urls")),
    path("admin/", admin.site.urls),
]

volah/urls.py
from django.urls import path

from .views import VolahHomeTemplateView
from .views import create_volunteer
from .views import VolunteerListView
from .views import VolunteerDetailView
from .views import VolunteerUpdateView
from .views import VolunteerDeleteView

from .views import create_organization
from .views import OrganizationListView
from .views import OrganizationDetailView
from .views import OrganizationUpdateView
from .views import OrganizationDeleteView


app_name = "volah"

urlpatterns = [
    # HomePage
    path("", VolahHomeTemplateView.as_view(), name="volah_home"),
    # Volunteer URLs
    path("create_volunteer/", create_volunteer, name="create_volunteer"),
    path("volunteers/", VolunteerListView.as_view(), name="list_volunteer"),
    path(
        "volunteer_detail/<int:pk>",
        VolunteerDetailView.as_view(),
        name="volunteer_detail",
    ),
    path(
        "volunteer_update/<int:pk>",
        VolunteerUpdateView.as_view(),
        name="volunteer_update",
    ),
    path(
        "volunteer_delete/<int:pk>",
        VolunteerDeleteView.as_view(),
        name="volunteer_delete",
    ),
    # Organization URLs
    path("create_organization/", create_organization, name="create_organization"),
    path("organizations/", OrganizationListView.as_view(), name="list_organization"),
    path(
        "organization_detail/<int:pk>",
        OrganizationDetailView.as_view(),
        name="organization_detail",
    ),
    path(
        "organization_update/<int:pk>",
        OrganizationUpdateView.as_view(),
        name="organization_update",
    ),
    path(
        "organization_delete/<int:pk>",
        OrganizationDeleteView.as_view(),
        name="organization_delete",
    ),
]

volah/models.py
from django.db import models
from django.core.validators import EmailValidator

# Create your models here.


countries = [
    (None, "-"),
    ("afghanistan", "Afghanistan"),
    ("albania", "Albania"),
    ("algeria", "Algeria"),
    ("andorra", "Andorra"),
    ("angola", "Angola"),
    ("antigua_and_barbuda", "Antigua and Barbuda"),
    ("argentina", "Argentina"),
    ("armenia", "Armenia"),
    ("australia", "Australia"),
    ("austria", "Austria"),
    ("azerbaijan", "Azerbaijan"),
    ("bahamas", "Bahamas"),
    ("bahrain", "Bahrain"),
    ("bangladesh", "Bangladesh"),
    ("barbados", "Barbados"),
    ("belarus", "Belarus"),
    ("belgium", "Belgium"),
    ("belize", "Belize"),
    ("benin", "Benin"),
    ("bhutan", "Bhutan"),
    ("bolivia", "Bolivia"),
    ("bosnia_and_herzegovina", "Bosnia and Herzegovina"),
    ("botswana", "Botswana"),
    ("brazil", "Brazil"),
    ("brunei", "Brunei"),
    ("bulgaria", "Bulgaria"),
    ("burkina_faso", "Burkina Faso"),
    ("burundi", "Burundi"),
    ("cote_d'ivoire", "Côte d'Ivoire"),
    ("cabo_verde", "Cabo Verde"),
    ("cambodia", "Cambodia"),
    ("cameroon", "Cameroon"),
    ("canada", "Canada"),
    ("central_african_republic", "Central African Republic"),
    ("chad", "Chad"),
    ("chile", "Chile"),
    ("china", "China"),
    ("colombia", "Colombia"),
    ("comoros", "Comoros"),
    ("congo", "Congo"),
    ("costa_rica", "Costa Rica"),
    ("croatia", "Croatia"),
    ("cuba", "Cuba"),
    ("cyprus", "Cyprus"),
    ("czechia", "Czechia"),
    ("democratic_republic_of_the_congo", "Democratic Republic of the Congo"),
    ("denmark", "Denmark"),
    ("djibouti", "Djibouti"),
    ("dominica", "Dominica"),
    ("dominican_republic", "Dominican Republic"),
    ("ecuador", "Ecuador"),
    ("egypt", "Egypt"),
    ("el_salvador", "El Salvador"),
    ("equatorial_guinea", "Equatorial Guinea"),
    ("eritrea", "Eritrea"),
    ("estonia", "Estonia"),
    ("eswatini", "Eswatini"),
    ("ethiopia", "Ethiopia"),
    ("fiji", "Fiji"),
    ("finland", "Finland"),
    ("france", "France"),
    ("gabon", "Gabon"),
    ("gambia", "Gambia"),
    ("georgia", "Georgia"),
    ("germany", "Germany"),
    ("ghana", "Ghana"),
    ("greece", "Greece"),
    ("grenada", "Grenada"),
    ("guatemala", "Guatemala"),
    ("guinea", "Guinea"),
    ("guinea_bissau", "Guinea-Bissau"),
    ("guyana", "Guyana"),
    ("haiti", "Haiti"),
    ("holy_see", "Holy See"),
    ("honduras", "Honduras"),
    ("hungary", "Hungary"),
    ("iceland", "Iceland"),
    ("india", "India"),
    ("indonesia", "Indonesia"),
    ("iran", "Iran"),
    ("iraq", "Iraq"),
    ("ireland", "Ireland"),
    ("israel", "Israel"),
    ("italy", "Italy"),
    ("jamaica", "Jamaica"),
    ("japan", "Japan"),
    ("jordan", "Jordan"),
    ("kazakhstan", "Kazakhstan"),
    ("kenya", "Kenya"),
    ("kiribati", "Kiribati"),
    ("kuwait", "Kuwait"),
    ("kyrgyzstan", "Kyrgyzstan"),
    ("laos", "Laos"),
    ("latvia", "Latvia"),
    ("lebanon", "Lebanon"),
    ("lesotho", "Lesotho"),
    ("liberia", "Liberia"),
    ("libya", "Libya"),
    ("liechtenstein", "Liechtenstein"),
    ("lithuania", "Lithuania"),
    ("luxembourg", "Luxembourg"),
    ("madagascar", "Madagascar"),
    ("malawi", "Malawi"),
    ("malaysia", "Malaysia"),
    ("maldives", "Maldives"),
    ("mali", "Mali"),
    ("malta", "Malta"),
    ("marshall_islands", "Marshall Islands"),
    ("mauritania", "Mauritania"),
    ("mauritius", "Mauritius"),
    ("mexico", "Mexico"),
    ("micronesia", "Micronesia"),
    ("moldova", "Moldova"),
    ("monaco", "Monaco"),
    ("mongolia", "Mongolia"),
    ("montenegro", "Montenegro"),
    ("morocco", "Morocco"),
    ("mozambique", "Mozambique"),
    ("myanmar (formerly_burma)", "Myanmar (formerly Burma)"),
    ("namibia", "Namibia"),
    ("nauru", "Nauru"),
    ("nepal", "Nepal"),
    ("netherlands", "Netherlands"),
    ("new_zealand", "New Zealand"),
    ("nicaragua", "Nicaragua"),
    ("niger", "Niger"),
    ("nigeria", "Nigeria"),
    ("north_korea", "North Korea"),
    ("north_macedonia", "North Macedonia"),
    ("norway", "Norway"),
    ("oman", "Oman"),
    ("pakistan", "Pakistan"),
    ("palau", "Palau"),
    ("palestine_state", "Palestine State"),
    ("panama", "Panama"),
    ("papua_new_guinea", "Papua New Guinea"),
    ("paraguay", "Paraguay"),
    ("peru", "Peru"),
    ("philippines", "Philippines"),
    ("poland", "Poland"),
    ("portugal", "Portugal"),
    ("qatar", "Qatar"),
    ("romania", "Romania"),
    ("russia", "Russia"),
    ("rwanda", "Rwanda"),
    ("saint_kitts_and_nevis", "Saint Kitts and Nevis"),
    ("saint_lucia", "Saint Lucia"),
    ("saint_vincent_and_the_grenadines", "Saint Vincent and the Grenadines"),
    ("samoa", "Samoa"),
    ("san_marino", "San Marino"),
    ("sao_tome_and_principe", "Sao Tome and Principe"),
    ("saudi_arabia", "Saudi Arabia"),
    ("senegal", "Senegal"),
    ("serbia", "Serbia"),
    ("seychelles", "Seychelles"),
    ("sierra_leone", "Sierra Leone"),
    ("singapore", "Singapore"),
    ("slovakia", "Slovakia"),
    ("slovenia", "Slovenia"),
    ("solomon_islands", "Solomon Islands"),
    ("somalia", "Somalia"),
    ("south_africa", "South Africa"),
    ("south_korea", "South Korea"),
    ("south_sudan", "South Sudan"),
    ("spain", "Spain"),
    ("sri_lanka", "Sri Lanka"),
    ("sudan", "Sudan"),
    ("suriname", "Suriname"),
    ("sweden", "Sweden"),
    ("switzerland", "Switzerland"),
    ("syria", "Syria"),
    ("tajikistan", "Tajikistan"),
    ("tanzania", "Tanzania"),
    ("thailand", "Thailand"),
    ("timor_leste", "Timor-Leste"),
    ("togo", "Togo"),
    ("tonga", "Tonga"),
    ("trinidad_and_tobago", "Trinidad and Tobago"),
    ("tunisia", "Tunisia"),
    ("turkey", "Turkey"),
    ("turkmenistan", "Turkmenistan"),
    ("tuvalu", "Tuvalu"),
    ("uganda", "Uganda"),
    ("ukraine", "Ukraine"),
    ("united_arab_emirates", "United Arab Emirates"),
    ("united_kingdom", "United Kingdom"),
    ("united_states_of_america", "United States of America"),
    ("uruguay", "Uruguay"),
    ("uzbekistan", "Uzbekistan"),
    ("vanuatu", "Vanuatu"),
    ("venezuela", "Venezuela"),
    ("vietnam", "Vietnam"),
    ("yemen", "Yemen"),
    ("zambia", "Zambia"),
    ("zimbabwe", "Zimbabwe"),
]

blood_types = [
    ("", " - "),
    ("a+", "A+"),
    ("a-", "A-"),
    ("b+", "B+"),
    ("b-", "B-"),
    ("ab+", "AB+"),
    ("ab-", "AB-"),
    ("o+", "O+"),
    ("o-", "O-"),
]

skills = [
    ("", "-"),
    ("first_aid", "First Aid"),
    ("comms", "Communications"),
    ("logistics", "Logistics"),
    ("fire_management_suppression", "Fire Management and Suppression"),
    ("search_and_rescue", "Search and Rescue"),
]


class Organization(models.Model):

    name = models.CharField(max_length=250)
    legal_status = models.CharField(max_length=250)
    hq_country = models.CharField(max_length=250, choices=countries)
    hq_state_province = models.CharField(max_length=250)
    address_line_1 = models.CharField(max_length=100)
    address_line_2 = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=15)

    org_website = models.URLField(blank=True)
    contact_name = models.CharField(max_length=150, blank=True)
    contact_surname = models.CharField(max_length=150, blank=True)
    contact_phone = models.CharField(max_length=15, blank=True)
    contact_email = models.EmailField(blank=True)

    def __str__(self):
        return f"{self.name}"


class Volunteer(models.Model):

    # MANDATORY
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    email = models.EmailField(validators=[EmailValidator()])
    phone = models.CharField(max_length=15)
    country = models.CharField(max_length=250, choices=countries)
    state_province = models.CharField(max_length=250)

    # OPTIONAL
    nickname = models.CharField(max_length=100, blank=True)
    blood_type = models.CharField(max_length=5, blank=True, choices=blood_types)
    skills = models.CharField(max_length=250, blank=True, choices=skills)
    organization = models.ForeignKey(
        "Organization", on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return f"{self.name} {self.surname}"

volah/forms.py
from django import forms


from .models import Volunteer, Organization


class DateInput(forms.DateInput):
    input_type = "date"


class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = "__all__"

        labels = {
            "name": "*Organization's Name",
            "legal_status": "*Org. Legal Status",
            "hq_country": "*Headquarters's Country",
            "hq_state_province": "*Headquarters's State/Province",
            "address_line_1": "*Address Line 1",
            "phone": "*Org. Phone",
        }


class VolunteerForm(forms.ModelForm):
    class Meta:
        model = Volunteer
        fields = "__all__"

        widgets = {
            "date_of_birth": DateInput(),
        }

        labels = {
            "name": "*First Name",
            "surname": "*Last Name",
            "date_of_birth": "*Date of Birth",
            "email": "*Email",
            "phone": "*Phone",
            "country": "*Country",
            "state_province": "*State/Province",
        }

volah/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)


from .models import Volunteer, Organization
from .forms import VolunteerForm, OrganizationForm

# Create your views here.


class VolahHomeTemplateView(TemplateView):
    template_name = "volah/volah_home.html"


def create_volunteer(request):
    if request.method == "POST":
        form = VolunteerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("volah:volah_home"))
    else:
        form = VolunteerForm()
    return render(request, "volah/volunteer_form.html", context={"form": form})


class VolunteerListView(ListView):
    model = Volunteer
    context_object_name = "volunteers_list"


class VolunteerDetailView(DetailView):
    model = Volunteer


class VolunteerUpdateView(UpdateView):
    model = Volunteer
    success_url = reverse_lazy("volah:list_volunteer")
    fields = "__all__"


class VolunteerDeleteView(DeleteView):
    model = Volunteer
    success_url = reverse_lazy("volah:list_volunteer")


def create_organization(request):

    if request.method == "POST":
        form = OrganizationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("volah:volah_home"))
    else:
        form = OrganizationForm()
    return render(request, "volah/organization_form.html", context={"form": form})


class OrganizationListView(ListView):
    model = Organization
    context_object_name = "organizations_list"


class OrganizationDetailView(DetailView):
    model = Organization


class OrganizationUpdateView(UpdateView):
    model = Organization
    success_url = reverse_lazy("volah:list_organization")
    fields = "__all__"


class OrganizationDeleteView(DeleteView):
    model = Organization
    success_url = reverse_lazy("volah:list_organization")

volah/templates/volah/organization_confirm_delete.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
    <h1>Are you sure you want to delete this ORGANIZATION?</h1>
    <h3>You will NOT be able to recover it's information!!!</h3>
    <h2>Organization info:</h2>
    <h4>{{ organization.name }} - {{ organization.legal_status }}</h4>
    <h4>From: {{ organization.hq_state_province }}/{{ organization.get_hq_country_display }}</h4>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="danger-btn">Yes, delete this organization.</button>
    </form>
    <div style="margin-top: 8px">
        <a href="{% url 'volah:list_organization' %}"><button class="normal-btn">CANCEL</button></a>
    </div>

{% endblock %}

volah/templates/volah/organization_detail.html
{% extends 'base/base.html' %}

{% block content %}

    <h1>ORGANIZATION DETAILS</h1>
    <td><a href="/volah/organization_update/{{ organization.id }}"><button class="normal-btn">Edit</button></a></td>
    <td><a href="/volah/organization_delete/{{ organization.id }}"><button class="normal-btn">Delete</button></a></td>

    {# ORGANIZATION'S NAME #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S NAME</h3>
        <p class="detail_data">{{ organization.name }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S LEGAL STATUS #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S LEGAL STATUS</h3>
        <p class="detail_data">{{ organization.legal_status }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S HQ COUNTRY #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S HQ COUNTRY</h3>
        <p class="detail_data">{{ organization.get_hq_country_display }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S HQ STATE/PROVINCE #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S HQ STATE/PROVINCE</h3>
        <p class="detail_data">{{ organization.hq_state_province }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S ADDRESS LINE 1 #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S ADDRESS LINE 1</h3>
        <p class="detail_data">{{ organization.address_line_1 }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S ADDRESS LINE 2 #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S ADDRESS LINE 2</h3>
        <p class="detail_data">{{ organization.address_line_2 }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S PHONE #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S PHONE</h3>
        <p class="detail_data">{{ organization.phone }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S WEBSITE #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S WEBSITE</h3>
        <p class="detail_data">{{ organization.org_website }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S CONTACT NAME #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S CONTACT NAME</h3>
        <p class="detail_data">{{ organization.contact_name }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S CONTACT SURNAME #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S CONTACT SURNAME</h3>
        <p class="detail_data">{{ organization.contact_surname }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S CONTACT PHONE #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S CONTACT PHONE</h3>
        <p class="detail_data">{{ organization.contact_phone }}</p>
    </div>
    <hr>

    {# ORGANIZATION'S CONTACT EMAIL #}
    <div class="detail_container">
        <h3 class="detail_label">ORGANIZATION'S CONTACT EMAIL</h3>
        <p class="detail_data">{{ organization.contact_email }}</p>
    </div>
    <hr>


{% endblock %}

volah/templates/volah/organization_form.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
    <h1>CREATE/EDIT ORGANIZATION</h1>
    <a href="{% url 'volah:list_organization' %}"><button class="normal-btn">Cancel</button></a>
    <form method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-field">
                {{ field.label_tag }}
            </div>
            {{ field }}
        {% endfor %}

        <div class="foot-note">Fields marked with * are mandatory.</div>

        <input type="submit">

    </form>

{% endblock %}

volah/templates/volah/organization_list.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
    <h1>ALL ORGANIZATIONS</h1>
    <a href="{% url 'volah:create_organization' %}"><button class="normal-btn">New</button></a>
    <a href=""><button class="normal-btn">Search</button></a>
    <a href="{% url 'volah:volah_home' %}"><button class="normal-btn">Back</button></a>
    <div class="table-container">
        <table class="all_items_table">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Legal Status</th>
                <th>Website</th>
                <th>Country</th>
                <th>State/Province</th>
                <th colspan="3">Actions</th>
            </tr>
            {% for organization in organizations_list %}
            <tr>
                <td>{{ organization.id }}</td>
                <td>{{ organization.name }}</td>
                <td>{{ organization.legal_status }}</td>
                <td>{{ organization.org_website }}</td>
                <td>{{ organization.hq_country }}</td>
                <td>{{ organization.hq_state_province }}</td>
                <td><a href=""><button class="normal-btn">Detail</button></a></td>
                <td><a href="/volah/organization_update/{{ organization.id }}"><button class="normal-btn">Edit</button></a></td>
                <td><a href="/volah/organization_delete/{{ organization.id }}"><button class="normal-btn">Delete</button></a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

volah/templates/volah/volah_home.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}

<h1>welcome to the volah module</h1>

<p style="font-size: 20px">Here you can create, view, edit, and delete information related to <b>organizations</b>.</p>
    <div>
        <h3>Organization Management</h3>
        <a href="{% url 'volah:create_organization' %}"><button class="normal-btn">Create</button></a>
        <a href="{% url 'volah:list_organization' %}"><button class="normal-btn">List All</button></a>
        <button class="normal-btn">Search</button>
    </div>

<p style="font-size: 20px">Here you can create, view, edit, and delete information related to <b>volunteers</b>.</p>
    <div>
        <h3>Volunteer Management</h3>
        <a href="{% url 'volah:create_volunteer' %}"><button class="normal-btn">Create</button></a>
        <a href="{% url 'volah:list_volunteer' %}"><button class="normal-btn">List All</button></a>
        <button class="normal-btn">Search</button>
    </div>

{% endblock %}

volah/templates/volah/volunteer_confirm_delete.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
    <h1>Are you sure you want to delete this Volunteer?</h1>
    <h3>You will NOT be able to recover it's information!!!</h3>
    <h2>Volunteer info:</h2>
    <h4>{{ volunteer.name }} {{ volunteer.surname }}</h4>
    <h4>From: {{ volunteer.state_province }}/{{ volunteer.get_country_display }}</h4>
    <h4>Born in: {{ volunteer.date_of_birth }}</h4>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="danger-btn">Yes, delete this user.</button>
    </form>
    <div style="margin-top: 8px">
        <a href="{% url 'volah:list_volunteer' %}"><button class="normal-btn">CANCEL</button></a>
    </div>

{% endblock %}

volah/templates/volah/volunteer_detail.html
{% extends 'base/base.html' %}

{% block content %}

    <h1>VOLUNTEER DETAILS</h1>
    <td><a href="/volah/volunteer_update/{{ volunteer.id }}"><button class="normal-btn">Edit</button></a></td>
    <td><a href="/volah/volunteer_delete/{{ volunteer.id }}"><button class="normal-btn">Delete</button></a></td>

    {# VOLUNTEER'S NAME #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S NAME</h3>
        <p class="detail_data">{{ volunteer.name }}</p>
    </div>
    <hr>

    {# VOLUNTEER'S SURNAME #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S SURNAME</h3>
        <p class="detail_data">{{ volunteer.surname }}</p>
    </div>
    <hr>

    {# VOLUNTEER'S DATE OF BIRTH #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S DATE OF BIRTH</h3>
        <p class="detail_data">{{ volunteer.date_of_birth }}</p>
    </div>
    <hr>

    {# VOLUNTEER'S EMAIL #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S EMAIL</h3>
        <p class="detail_data">{{ volunteer.email }}</p>
    </div>
    <hr>

    {# VOLUNTEER'S PHONE #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S PHONE</h3>
        <p class="detail_data">{{ volunteer.phone }}</p>
    </div>
    <hr>

    {# VOLUNTEER'S COUNTRY #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S COUNTRY</h3>
        <p class="detail_data">{{ volunteer.get_country_display }}</p>
    </div>
    <hr>

    {# VOLUNTEER'S STATE/PROVINCE #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S STATE/PROVINCE</h3>
        <p class="detail_data">{{ volunteer.state_province }}</p>
    </div>
    <hr>

    {# VOLUNTEER'S NICKNAME #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S NICKNAME</h3>
        <p class="detail_data">{{ volunteer.nickname }}</p>
    </div>
    <hr>

    {# VOLUNTEER'S BLOOD TYPE #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S BLOOD TYPE</h3>
        <p class="detail_data">{{ volunteer.get_blood_type_display }}</p>
    </div>
    <hr>

    {# VOLUNTEER'S PRIMARY SKILL #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S PRIMARY SKILL</h3>
        <p class="detail_data">{{ volunteer.get_skills_display }}</p>
    </div>
    <hr>

    {# VOLUNTEER'S CONECTED ORGANIZATION #}
    <div class="detail_container">
        <h3 class="detail_label">VOLUNTEER'S ORGANIZATION</h3>
        <p class="detail_data">{{ volunteer.organization }}</p>
    </div>
    <hr>


{% endblock %}

volah/templates/volah/volunteer_form.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
    <h1>CREATE/EDIT VOLUNTEER</h1>
    <a href="{% url 'volah:list_volunteer' %}"><button class="normal-btn">Cancel</button></a>
    <form method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-field">
                {{ field.label_tag }}
            </div>
            {{ field }}
        {% endfor %}

        <div class="foot-note">Fields marked with * are mandatory.</div>

        <input type="submit">

    </form>

{% endblock %}

volah/templates/volah/volunteer_list.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
    <h1>ALL VOLUNTEERS</h1>
    <a href="{% url 'volah:create_volunteer' %}"><button class="normal-btn">New</button></a>
    <a href=""><button class="normal-btn">Search</button></a>
    <a href="{% url 'volah:volah_home' %}"><button class="normal-btn">Back</button></a>
    <div class="table-container">
        <table class="all_items_table">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Email</th>
                <th>Country</th>
                <th>State/Province</th>
                <th>Organization</th>
                <th colspan="3">Actions</th>
            </tr>
            {% for volunteer in volunteers_list %}
            <tr>
                <td>{{ volunteer.id }}</td>
                <td>{{ volunteer.name }}</td>
                <td>{{ volunteer.surname }}</td>
                <td>{{ volunteer.email }}</td>
                <td>{{ volunteer.country }}</td>
                <td>{{ volunteer.state_province }}</td>
                <td>{{ volunteer.organization }}</td>
                <td><a href=""><button class="normal-btn">Detail</button></a></td>
                <td><a href="/volah/volunteer_update/{{ volunteer.id }}"><button class="normal-btn">Edit</button></a></td>
                <td><a href="/volah/volunteer_delete/{{ volunteer.id }}"><button class="normal-btn">Delete</button></a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}