helpout/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.IndexTemplateView.as_view(), name="main_menu"),
    path("volah/", include("volah.urls")),
    path("admin/", admin.site.urls),
]

volah/urls.py
from django.urls import path

from .views import VolahHomeTemplateView
from .views import create_volunteer
from .views import VolunteerListView
from .views import VolunteerDetailView
from .views import VolunteerUpdateView
from .views import VolunteerDeleteView

from .views import create_organization
from .views import OrganizationListView
from .views import OrganizationDetailView
from .views import OrganizationUpdateView
from .views import OrganizationDeleteView


app_name = "volah"

urlpatterns = [
    # HomePage
    path("", VolahHomeTemplateView.as_view(), name="volah_home"),
    # Volunteer URLs
    path("create_volunteer/", create_volunteer, name="create_volunteer"),
    path("volunteers/", VolunteerListView.as_view(), name="list_volunteer"),
    path(
        "volunteer_detail/<int:pk>",
        VolunteerDetailView.as_view(),
        name="volunteer_detail",
    ),
    path(
        "volunteer_update/<int:pk>",
        VolunteerUpdateView.as_view(),
        name="volunteer_update",
    ),
    path(
        "volunteer_delete/<int:pk>",
        VolunteerDeleteView.as_view(),
        name="volunteer_delete",
    ),
    # Organization URLs
    path("create_organization/", create_organization, name="create_organization"),
    path("organizations/", OrganizationListView.as_view(), name="list_organization"),
    path(
        "organization_detail/<int:pk>",
        OrganizationDetailView.as_view(),
        name="organization_detail",
    ),
    path(
        "organization_update/<int:pk>",
        OrganizationUpdateView.as_view(),
        name="organization_update",
    ),
    path(
        "organization_delete/<int:pk>",
        OrganizationDeleteView.as_view(),
        name="organization_delete",
    ),
]

helpout/views.py
from django.views.generic import TemplateView


class IndexTemplateView(TemplateView):
    template_name = "helpout/home.html"

helpout/templates/base/base.html
{% load static  %}

{% block base %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'base/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=JetBrains_Mono">
    {% block stylesheet %} {% endblock %}
    <title>project helpout</title>
</head>
<body>
    <div class="container">
        <header>
            <a href="{% url 'main_menu' %}"><img id="logo" alt="hand-logo" src="{% static 'img/hands-up.png' %}"></a>
            <h3 id="main-title">the helpout project</h3>
            <nav id="menu-header">
                <a href="{% url 'main_menu' %}"><button class="btn-header">Main Menu</button></a>
                <button class="btn-header">My Panel</button>
                <button class="btn-header">Settings</button>
                <button class="btn-header">Logout</button>
            </nav>
        </header>
        <div class="sidenav">
            <a class="nav-title" href="#" style="pointer-events: none">MODULES</a>
            <a class="nav-option" href="{% url 'volah:volah_home' %}">Volah</a>
            <a class="nav-title" href="#" style="pointer-events: none">Coming soon:</a>
            <a class="nav-option" href="#" style="pointer-events: none">Projects Module</a>
        </div>
        <main>
            {% block content %}

            {% endblock %}
        </main>
    </div>

</body>
</html>
{% endblock %}